name: Publish Python distribution packages to PypI.

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
      - name: Build a binary wheel and a source tarball
        run: uv build
      - name: Publish a Python distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          skip-existing: true